/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	opsv1alpha1 "go.virtual-secrets.dev/taskqueue/apis/ops/v1alpha1"
	versioned "go.virtual-secrets.dev/taskqueue/client/clientset/versioned"
	internalinterfaces "go.virtual-secrets.dev/taskqueue/client/informers/externalversions/internalinterfaces"
	v1alpha1 "go.virtual-secrets.dev/taskqueue/client/listers/ops/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PendingTaskInformer provides access to a shared informer and lister for
// PendingTasks.
type PendingTaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PendingTaskLister
}

type pendingTaskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPendingTaskInformer constructs a new informer for PendingTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPendingTaskInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPendingTaskInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPendingTaskInformer constructs a new informer for PendingTask type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPendingTaskInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpsV1alpha1().PendingTasks().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpsV1alpha1().PendingTasks().Watch(context.TODO(), options)
			},
		},
		&opsv1alpha1.PendingTask{},
		resyncPeriod,
		indexers,
	)
}

func (f *pendingTaskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPendingTaskInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pendingTaskInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&opsv1alpha1.PendingTask{}, f.defaultInformer)
}

func (f *pendingTaskInformer) Lister() v1alpha1.PendingTaskLister {
	return v1alpha1.NewPendingTaskLister(f.Informer().GetIndexer())
}
