/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeops.dev/taskqueue/apis/ops/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePendingTasks implements PendingTaskInterface
type FakePendingTasks struct {
	Fake *FakeOpsV1alpha1
}

var pendingtasksResource = v1alpha1.SchemeGroupVersion.WithResource("pendingtasks")

var pendingtasksKind = v1alpha1.SchemeGroupVersion.WithKind("PendingTask")

// Get takes name of the pendingTask, and returns the corresponding pendingTask object, and an error if there is any.
func (c *FakePendingTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PendingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(pendingtasksResource, name), &v1alpha1.PendingTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PendingTask), err
}

// List takes label and field selectors, and returns the list of PendingTasks that match those selectors.
func (c *FakePendingTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PendingTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(pendingtasksResource, pendingtasksKind, opts), &v1alpha1.PendingTaskList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PendingTaskList{ListMeta: obj.(*v1alpha1.PendingTaskList).ListMeta}
	for _, item := range obj.(*v1alpha1.PendingTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pendingTasks.
func (c *FakePendingTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(pendingtasksResource, opts))
}

// Create takes the representation of a pendingTask and creates it.  Returns the server's representation of the pendingTask, and an error, if there is any.
func (c *FakePendingTasks) Create(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.CreateOptions) (result *v1alpha1.PendingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(pendingtasksResource, pendingTask), &v1alpha1.PendingTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PendingTask), err
}

// Update takes the representation of a pendingTask and updates it. Returns the server's representation of the pendingTask, and an error, if there is any.
func (c *FakePendingTasks) Update(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (result *v1alpha1.PendingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(pendingtasksResource, pendingTask), &v1alpha1.PendingTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PendingTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePendingTasks) UpdateStatus(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (*v1alpha1.PendingTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(pendingtasksResource, "status", pendingTask), &v1alpha1.PendingTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PendingTask), err
}

// Delete takes name of the pendingTask and deletes it. Returns an error if one occurs.
func (c *FakePendingTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(pendingtasksResource, name, opts), &v1alpha1.PendingTask{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePendingTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(pendingtasksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PendingTaskList{})
	return err
}

// Patch applies the patch and returns the patched pendingTask.
func (c *FakePendingTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PendingTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(pendingtasksResource, name, pt, data, subresources...), &v1alpha1.PendingTask{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PendingTask), err
}
