//go:build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectPhaseRules) DeepCopyInto(out *ObjectPhaseRules) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectPhaseRules.
func (in *ObjectPhaseRules) DeepCopy() *ObjectPhaseRules {
	if in == nil {
		return nil
	}
	out := new(ObjectPhaseRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingTask) DeepCopyInto(out *PendingTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingTask.
func (in *PendingTask) DeepCopy() *PendingTask {
	if in == nil {
		return nil
	}
	out := new(PendingTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PendingTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingTaskList) DeepCopyInto(out *PendingTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PendingTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingTaskList.
func (in *PendingTaskList) DeepCopy() *PendingTaskList {
	if in == nil {
		return nil
	}
	out := new(PendingTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PendingTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingTaskSpec) DeepCopyInto(out *PendingTaskSpec) {
	*out = *in
	out.TaskType = in.TaskType
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingTaskSpec.
func (in *PendingTaskSpec) DeepCopy() *PendingTaskSpec {
	if in == nil {
		return nil
	}
	out := new(PendingTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingTaskStatus) DeepCopyInto(out *PendingTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingTaskStatus.
func (in *PendingTaskStatus) DeepCopy() *PendingTaskStatus {
	if in == nil {
		return nil
	}
	out := new(PendingTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueue) DeepCopyInto(out *TaskQueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueue.
func (in *TaskQueue) DeepCopy() *TaskQueue {
	if in == nil {
		return nil
	}
	out := new(TaskQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskQueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueueList) DeepCopyInto(out *TaskQueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskQueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueueList.
func (in *TaskQueueList) DeepCopy() *TaskQueueList {
	if in == nil {
		return nil
	}
	out := new(TaskQueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskQueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueueSpec) DeepCopyInto(out *TaskQueueSpec) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]UnitTask, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueueSpec.
func (in *TaskQueueSpec) DeepCopy() *TaskQueueSpec {
	if in == nil {
		return nil
	}
	out := new(TaskQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueueStatus) DeepCopyInto(out *TaskQueueStatus) {
	*out = *in
	if in.TriggeredTasksStatus != nil {
		in, out := &in.TriggeredTasksStatus, &out.TriggeredTasksStatus
		*out = make(map[string]map[string]TaskPhase, len(*in))
		for key, val := range *in {
			var outVal map[string]TaskPhase
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]TaskPhase, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueueStatus.
func (in *TaskQueueStatus) DeepCopy() *TaskQueueStatus {
	if in == nil {
		return nil
	}
	out := new(TaskQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypedResourceReference) DeepCopyInto(out *TypedResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypedResourceReference.
func (in *TypedResourceReference) DeepCopy() *TypedResourceReference {
	if in == nil {
		return nil
	}
	out := new(TypedResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnitTask) DeepCopyInto(out *UnitTask) {
	*out = *in
	out.Type = in.Type
	out.Rules = in.Rules
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnitTask.
func (in *UnitTask) DeepCopy() *UnitTask {
	if in == nil {
		return nil
	}
	out := new(UnitTask)
	in.DeepCopyInto(out)
	return out
}
