/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "go.virtual-secrets.dev/taskqueue/apis/ops/v1alpha1"
	scheme "go.virtual-secrets.dev/taskqueue/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PendingTasksGetter has a method to return a PendingTaskInterface.
// A group's client should implement this interface.
type PendingTasksGetter interface {
	PendingTasks() PendingTaskInterface
}

// PendingTaskInterface has methods to work with PendingTask resources.
type PendingTaskInterface interface {
	Create(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.CreateOptions) (*v1alpha1.PendingTask, error)
	Update(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (*v1alpha1.PendingTask, error)
	UpdateStatus(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (*v1alpha1.PendingTask, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PendingTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PendingTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PendingTask, err error)
	PendingTaskExpansion
}

// pendingTasks implements PendingTaskInterface
type pendingTasks struct {
	client rest.Interface
}

// newPendingTasks returns a PendingTasks
func newPendingTasks(c *OpsV1alpha1Client) *pendingTasks {
	return &pendingTasks{
		client: c.RESTClient(),
	}
}

// Get takes name of the pendingTask, and returns the corresponding pendingTask object, and an error if there is any.
func (c *pendingTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PendingTask, err error) {
	result = &v1alpha1.PendingTask{}
	err = c.client.Get().
		Resource("pendingtasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PendingTasks that match those selectors.
func (c *pendingTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PendingTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PendingTaskList{}
	err = c.client.Get().
		Resource("pendingtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pendingTasks.
func (c *pendingTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("pendingtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pendingTask and creates it.  Returns the server's representation of the pendingTask, and an error, if there is any.
func (c *pendingTasks) Create(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.CreateOptions) (result *v1alpha1.PendingTask, err error) {
	result = &v1alpha1.PendingTask{}
	err = c.client.Post().
		Resource("pendingtasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pendingTask).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pendingTask and updates it. Returns the server's representation of the pendingTask, and an error, if there is any.
func (c *pendingTasks) Update(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (result *v1alpha1.PendingTask, err error) {
	result = &v1alpha1.PendingTask{}
	err = c.client.Put().
		Resource("pendingtasks").
		Name(pendingTask.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pendingTask).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pendingTasks) UpdateStatus(ctx context.Context, pendingTask *v1alpha1.PendingTask, opts v1.UpdateOptions) (result *v1alpha1.PendingTask, err error) {
	result = &v1alpha1.PendingTask{}
	err = c.client.Put().
		Resource("pendingtasks").
		Name(pendingTask.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pendingTask).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pendingTask and deletes it. Returns an error if one occurs.
func (c *pendingTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("pendingtasks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pendingTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("pendingtasks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pendingTask.
func (c *pendingTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PendingTask, err error) {
	result = &v1alpha1.PendingTask{}
	err = c.client.Patch(pt).
		Resource("pendingtasks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
